# Generated by Django 5.1.4 on 2024-12-21 16:40

import django.db.models.deletion
from django.db import migrations, models


# Functions from previous migrations moved here
def create_default_topic(apps, schema_editor):
    Topic = apps.get_model('tensorflow_api', 'Topic')
    Topic.objects.get_or_create(
        id=1,
        defaults={
            "name": "Default Topic",
            "description": "Default topic for migration purposes."
        }
    )


class Migration(migrations.Migration):

    replaces = [
        ('tensorflow_api', '0001_initial'),
        ('tensorflow_api', '0002_question_image'),
        ('tensorflow_api', '0003_question_language'),
        ('tensorflow_api', '0004_remove_question_language_and_more'),
        ('tensorflow_api', '0005_question_language'),
        ('tensorflow_api', '0006_translation'),
        ('tensorflow_api', '0007_alter_translation_unique_together'),
        ('tensorflow_api', '0008_translation_is_ai_generated'),
        ('tensorflow_api', '0010_topic_alter_question_topic'),
        ('tensorflow_api', '0009_topic_question_topic'),
        ('tensorflow_api', '0011_merge_20241221_1551'),
        ('tensorflow_api', '0012_alter_topic_id')
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('original_text_provided', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='option_images/')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tensorflow_api.question')),
                ('original_text_provided', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tensorflow_api.question')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tensorflow_api.option')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_ai_generated', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tensorflow_api.topic'),
        ),
        migrations.RunPython(
            code=create_default_topic,
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
