# Generated by Django 5.1.4 on 2024-12-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tensorflow_api', '0003_question_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
        migrations.AddField(
            model_name='option',
            name='original_text_provided',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='original_text_provided',
            field=models.BooleanField(default=True),
        ),
    ]
