# Generated by Django 5.1.4 on 2024-12-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tensorflow_api', '0009_topic_question_topic'),
        ('tensorflow_api', '0010_topic_alter_question_topic'),
    ]

    operations = [
    ]
