# Generated by Django 5.1.4 on 2024-12-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tensorflow_api', '0011_merge_20241221_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
